CREATE TABLE   IF NOT EXISTS  `pub_YLnum` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ylNum` varchar(255) DEFAULT NULL,
  `pn` varchar(255) DEFAULT NULL,
  `sku` varchar(255) DEFAULT NULL,
  `asin` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `supplier` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `subcategory` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `quantity` varchar(255) DEFAULT NULL,
  `wireLength` varchar(255) DEFAULT NULL,
  `terminalMaterial` varchar(255) DEFAULT NULL,
  `externalMaterial` varchar(255) DEFAULT NULL,
  `mouths` varchar(255) DEFAULT NULL,
  `technology` varchar(255) DEFAULT NULL,
  `capacity` varchar(255) DEFAULT NULL,
  `adapterType` varchar(255) DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;