module.exports = {
	Pub_Ylnum_N: [
		'YlNum',
		'sku',
		'asin',
		'name',
		'supplier',
		'category',
		'subcategory',
		'state',
		'color',
		'quantity',
		'WireLength',
		'TerminalMaterial',
		'ExternalMaterial',
		'mouths',
		'Technology',
		'capacity',
		'AdapterType',
	],
	Asc_Sponsored_Products_Advertised_N: [],
	Asc_Bussiness_Report_N: [],
}
